-- =============================================
-- TABELA DE NOTIFICAÇÕES
-- =============================================

CREATE TABLE public.notificacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Quem recebe a notificação
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Tipo da notificação
  tipo text NOT NULL CHECK (tipo IN ('venda', 'aniversario')),
  
  -- Título curto (ex: "Nova venda registrada", "Aniversário de João")
  titulo text NOT NULL,
  
  -- Mensagem descritiva (ex: "Venda de R$ 143,00 para João Silva", "João Silva faz aniversário hoje! 🎂")
  mensagem text NOT NULL,
  
  -- Referência opcional (ID da venda, ID do cliente, etc.)
  referencia_id text NULL,
  
  -- Status de leitura
  lida boolean NOT NULL DEFAULT false,
  
  -- Timestamps
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Índices para performance
CREATE INDEX idx_notificacoes_user_id ON public.notificacoes(user_id);
CREATE INDEX idx_notificacoes_lida ON public.notificacoes(user_id, lida);
CREATE INDEX idx_notificacoes_created ON public.notificacoes(user_id, created_at DESC);

-- =============================================
-- RLS (ROW LEVEL SECURITY)
-- =============================================

-- Ativar RLS
ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;

-- SELECT: Cada usuário só vê SUAS notificações
CREATE POLICY "notificacoes_select_own"
ON public.notificacoes
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

-- INSERT: O servidor pode criar notificações para qualquer usuário
CREATE POLICY "notificacoes_insert_authenticated"
ON public.notificacoes
FOR INSERT
TO authenticated
WITH CHECK (true);

-- UPDATE: Cada usuário só marca SUAS notificações como lidas
CREATE POLICY "notificacoes_update_own"
ON public.notificacoes
FOR UPDATE
TO authenticated
USING (user_id = auth.uid());

-- DELETE: Cada usuário só deleta SUAS notificações
CREATE POLICY "notificacoes_delete_own"
ON public.notificacoes
FOR DELETE
TO authenticated
USING (user_id = auth.uid());

-- =============================================
-- TABELA CLIENTES (CRM)
-- =============================================

-- Adicionar coluna data_nascimento na tabela de clientes
ALTER TABLE public.crm_fermaquinas
ADD COLUMN IF NOT EXISTS data_nascimento date NULL;

-- =============================================
-- FUNÇÃO RPC PARA ANIVERSARIANTES
-- =============================================

-- Criar function no Supabase para buscar aniversariantes de hoje
CREATE OR REPLACE FUNCTION public.aniversariantes_hoje()
RETURNS SETOF crm_fermaquinas
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT * FROM crm_fermaquinas
  WHERE data_nascimento IS NOT NULL
    AND deleted_at IS NULL
    AND EXTRACT(month FROM data_nascimento) = EXTRACT(month FROM CURRENT_DATE)
    AND EXTRACT(day FROM data_nascimento) = EXTRACT(day FROM CURRENT_DATE);
$$;
